# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a845032f0732019c83958a318d67c08a06d2945963590cc388b4948b5f1a1648251f6a96f4efe4d733d459f33a6af89de5323344c7586ee0fbb5911bc77bc27

test:
  secret_key_base: b0ec6c21684c5a25bf094b3d92535a8e7b1e7ba5bc3ed7d8168b0efba05a2ef8d860f5634961c69622aa81caee3a3f64059c1bf72c92f235c40001b2da41b8ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
